config/routes.rb
RailsMoronDummy::Application.routes.draw do
  resources :thinking_ofs

end

app/models/moron_guess.rb
class MoronGuess < ActiveRecord::Base
  belongs_to :thinking_of
end

app/models/thinking_of.rb
class ThinkingOf < ActiveRecord::Base
    validates_numericality_of :number, :less_than_or_equal_to => 10, :greater_than_or_equal_to => 1
    has_many :moron_guesses
    after_save :start_guessing
    def guessed
        if self.moron_guesses.count == 0
            return 'Nope'
        else
            return "#{self.moron_guesses.count} tries"
        end
    end

    def bg_start_guessing
        self.delay.start_guessing
    end
    def start_guessing
        guess = 0
        self.moron_guesses.delete_all
        while guess != self.number do
            sleep(1)
            guess = 1+rand(10)
            puts "Durrr, is it #{guess}?"
            guess_obj = MoronGuess.new(:thinking_of => self,
                                       :guess => guess)
            self.moron_guesses << guess_obj
        end
        puts 'Moron guesses:',self.moron_guesses.count
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/thinking_ofs_controller.rb
class ThinkingOfsController < ApplicationController
  # GET /thinking_ofs
  # GET /thinking_ofs.xml
  def index
    @thinking_ofs = ThinkingOf.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @thinking_ofs }
    end
  end

  # GET /thinking_ofs/1
  # GET /thinking_ofs/1.xml
  def show
    @thinking_of = ThinkingOf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @thinking_of }
    end
  end

  # GET /thinking_ofs/new
  # GET /thinking_ofs/new.xml
  def new
    @thinking_of = ThinkingOf.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @thinking_of }
    end
  end

  # GET /thinking_ofs/1/edit
  def edit
    @thinking_of = ThinkingOf.find(params[:id])
  end

  # POST /thinking_ofs
  # POST /thinking_ofs.xml
  def create
    @thinking_of = ThinkingOf.new(params[:thinking_of])

    respond_to do |format|
      if @thinking_of.save
        format.html { redirect_to(@thinking_of, :notice => 'Thinking of was successfully created.') }
        format.xml  { render :xml => @thinking_of, :status => :created, :location => @thinking_of }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @thinking_of.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /thinking_ofs/1
  # PUT /thinking_ofs/1.xml
  def update
    @thinking_of = ThinkingOf.find(params[:id])

    respond_to do |format|
      if @thinking_of.update_attributes(params[:thinking_of])
        format.html { redirect_to(@thinking_of, :notice => 'Thinking of was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @thinking_of.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /thinking_ofs/1
  # DELETE /thinking_ofs/1.xml
  def destroy
    @thinking_of = ThinkingOf.find(params[:id])
    @thinking_of.destroy

    respond_to do |format|
      format.html { redirect_to(thinking_ofs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thinking_ofs_helper.rb
module ThinkingOfsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMoronDummy</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thinking_ofs/_form.html.erb
<%= form_for(@thinking_of) do |f| %>
  <% if @thinking_of.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thinking_of.errors.count, "error") %> prohibited this thinking_of from being saved:</h2>

      <ul>
      <% @thinking_of.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thinking_ofs/edit.html.erb
<h1>Editing thinking_of</h1>

<%= render 'form' %>

<%= link_to 'Show', @thinking_of %> |
<%= link_to 'Back', thinking_ofs_path %>

app/views/thinking_ofs/index.html.erb
<h1>Listing thinking_ofs</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Guessed?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @thinking_ofs.each do |thinking_of| %>
  <tr>
    <td><%= thinking_of.number %></td>
    <td><%= thinking_of.guessed %></td>
    <td><%= link_to 'Show', thinking_of %></td>
    <td><%= link_to 'Edit', edit_thinking_of_path(thinking_of) %></td>
    <td><%= link_to 'Destroy', thinking_of, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thinking of', new_thinking_of_path %>

app/views/thinking_ofs/new.html.erb
<h1>New thinking_of</h1>

<%= render 'form' %>

<%= link_to 'Back', thinking_ofs_path %>

app/views/thinking_ofs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @thinking_of.number %>
</p>


<%= link_to 'Edit', edit_thinking_of_path(@thinking_of) %> |
<%= link_to 'Back', thinking_ofs_path %>